### ISSUE TITLE
Scheduler is not working

### ISSUE THREAD

**Issue by Msiavashi** [google/ghost-userspace#1]
Hi,

My question might be naive but I'm trying to execute some experiments with the provided schedulers (e.g. fifo scheduler, shinjuku scheduler). I've noticed that the agent's executes and initializes the cores successfully, however it appears to me that it does not schedule any process. I have placed a few `printf`s in the `Enqueue` method as well as the constructor. The `printf` of the constructor prints, once the scheduler is initialized, however the prints inside of the `enqueue` method, do not get called at all. No significant difference in performance observed as well.

I have a web server running on the `SCHED_FIFO` policy with `99` priority.

The provided tests also pass but the scheduler does not log anything except for core mapping and initialization prints.

I also debugged the kernel to see if the `SCHED_GHOST` policy of the kernel works. It seems the kernel schedules the agent perfectly,  however, the agent does not schedule the real-time (or any) of my processes.

So simply my question is, how to make sure the agent's scheduler is working correctly when the `enqueue` method seems not to be called at all?

I appreciate your help.

Thanks

**Comment by neelnatu** [comment]
Hi Mohammad, are you trying to schedule the web server (with SCHED_FIFO policy) using one of the ghost schedulers (say fifo_scheduler)?

If yes, then you'll need to move the application threads into the ghost scheduling class. All of the various ghost schedulers only schedule tasks with policy == SCHED_GHOST.

There's a couple of ways to move application threads into ghost (for your use case I'll recommend #3):
1. modify the application itself to create GhostThreads but unless you are writing something from scratch this is usually not feasible.
2. have the agent monitor cgroups tagged with a special file to indicate that all tasks in the cgroup should be moved into ghost (we use this approach extensively but haven't pushed it into the open source repository).
3. move the application threads into ghost with a command like tool. I am pasting the source code for one such tool we use internally. Let us know if this is useful and we can add that to our github repository.

<snip>
#include <errno.h>
#include <fcntl.h>
#include <sched.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <unistd.h>

#define SCHED_GHOST 18

static const char *enclave_path = "/sys/fs/ghost/enclave_1/ctl";
static char *progname;

static void usage(int rc) {
  fprintf(stderr, "Usage: %s <policy>\n", progname);
  fprintf(stderr, "To push tasks into ghOSt:\n");
  fprintf(stderr, "    $ cat /dev/cgroup/cpu/mine/tasks | %s 18\n", progname);
  fprintf(stderr, "To push tasks into CFS\n");
  fprintf(stderr, "    $ cat /dev/cgroup/cpu/your/tasks | %s 0\n", progname);
  exit(rc);
}

// For various glibc reasons, this isn't available in glibc/grte.  Including
// uapi/sched.h or sched/types.h will run into conflicts on sched_param.
struct sched_attr {
  uint32_t size;
  uint32_t sched_policy;
  uint64_t sched_flags;
  int32_t sched_nice;
  uint32_t sched_priority;  // overloaded for is/is not an agent
  uint64_t sched_runtime;   // overloaded for enclave ctl fd
  uint64_t sched_deadline;
  uint64_t sched_period;
};
#define SCHED_FLAG_RESET_ON_FORK 0x01

int sched_enter_ghost(pid_t pid, int enclave_fd) {
  // Enter ghOSt sched class.
  struct sched_attr attr = {
      .size = sizeof(sched_attr),
      .sched_policy = SCHED_GHOST,
      .sched_priority = 0,  // GHOST_SCHED_TASK_PRIO
      .sched_runtime = static_cast<uint64_t>(enclave_fd),
  };
  return syscall(__NR_sched_setattr, pid, &attr, /*flags=*/0);
}

int sched_enter_other(pid_t pid, int policy) {
  struct sched_param param = { 0 };
  return sched_setscheduler(pid, policy, &param);
}

int main(int argc, char *argv[])
{
  pid_t pid;
  int policy, enclave_fd = -1;

  progname = basename(argv[0]);

  if (argc != 2)
    usage(1);

  policy = atoi(argv[1]);
  if (policy == SCHED_GHOST) {
    enclave_fd = open(enclave_path, O_RDWR);
    if (enclave_fd < 0) {
      fprintf(stderr, "open(%s): %s\n", enclave_path, strerror(errno));
      exit(1);
    }
  }

  fprintf(stderr, "Setting scheduling policy to %d\n", policy);

  while (fscanf(stdin, "%d\n", &pid) != EOF) {
    if (sched_getscheduler(pid) == policy)
      continue;

    int ret;
    fprintf(stderr, "pid: %d\n", pid);
    if (policy == SCHED_GHOST)
      ret = sched_enter_ghost(pid, enclave_fd);
    else
      ret = sched_enter_other(pid, policy);

    // Trust but verify.
    if (!ret) {
      int actual = sched_getscheduler(pid);
      if (actual != policy) {
        fprintf(stderr, "scheduling policy of %d: want %d, got %d: %s\n",
                pid, policy, actual, strerror(errno));
      }
    } else {
      fprintf(stderr, "setscheduler(%d) failed: %s\n", pid, strerror(errno));
      exit(1);
    }
  }

  exit(0);
}
</snip>

**Comment by neelnatu** [comment]
Hmm, once you move all threads of the webserver into ghost any _new_ threads created by that application should automatically start out in the ghost sched_class. You can verify this by periodically doing a 'grep policy /proc/<pid>/sched' for all tasks you get via `ls /proc/$(pidof webserver_app)/task`.

Is that not happening in your case?

**Comment by Msiavashi** [comment]
> Hmm, once you move all threads of the webserver into ghost any _new_ threads created by that application should automatically start out in the ghost sched_class. You can verify this by periodically doing a 'grep policy /proc//sched' for all tasks you get via `ls /proc/$(pidof webserver_app)/task`.
> 
> Is that not happening in your case?

Hi Neel,

You're right. I double checked and It's working as you said. However, The throughout drops significantly with FIFO. Probably because of its non-preemptive implementation.

Anyway, I'm trying to run the Shinjuku to compare the performance. But stillll have some problems with running it. I'll ask for your help if I couldn't fix it today.

Thanks

**Comment by neelnatu** [comment]
On Sun, Oct 31, 2021 at 4:03 PM Mohammad Siavashi ***@***.***>
wrote:

> Hmm, once you move all threads of the webserver into ghost any *new*
> threads created by that application should automatically start out in the
> ghost sched_class. You can verify this by periodically doing a 'grep policy
> /proc//sched' for all tasks you get via ls /proc/$(pidof
> webserver_app)/task.
>
> Is that not happening in your case?
>
> Hi Neel,
>
> You're right. I double checked and It's working as you said. However, The
> throughout drops significantly with FIFO. Probably because of its
> non-preemptive implementation.
>
Yes, that's not surprising. In addition to being non-preemptive, the
fifo_scheduler also does not do any load balancing between cpus at runtime
(it statically assigns a task to a cpu and it stays there until it dies or
departs). It's goal is to serve as a demonstration of a per-cpu scheduling
model in ghost.


> Anyway, I'm trying to run the Shinjuku to compare the performance. But
> stillll have some problems with running it. I'll ask for your help if I
> couldn't fix it today.
>
Yes, sounds good.

best
Neel

**Comment by jackhumphries** [comment]
For Shinjuku, here are the main gotchas:

1. Integrate your web server with the PrioTable and make sure each pthread is marked as runnable.
2. Set the preemption time slice properly in Shinjuku (this is specified to the Shinjuku agent process via the --preemption_time_slice command line arg). The default is 50 µs but you probably want something higher than that for a web server.

**Comment by jackhumphries** [comment]
And just to be clear, Shinjuku is a _centralized_ scheduler that has preemption. So you should get better QPS for your web server, though the spinning Shinjuku global agent will take up a logical core.

**Comment by Msiavashi** [comment]
Thanks,

Just started to get the Shinjuku running, for now, it seems the `UnzipPar` function in the `Setup.py` file returns a wrong `par` path. It return the `shinjuku.runfiles` instead of `shinjuku.par` path. Now that it's fixed, it progressed to the `RunAllExperiments` function but it's throwing an error related to the number of cores: `lib/topology.h:472(20266) CHECK FAILED: cpu < cpus_.size() [8 >= 8]`

I'm looking into it.

**Comment by jackhumphries** [comment]
That's likely because the Shinjuku experiments require a machine with at least 8 logical cores. You can lower this by updating `_NUM_CPUS` in shinjuku.py.

**Comment by jackhumphries** [comment]
Also take a look at the `_FIRST_CPU` variable and related options in options.py. We tend to affine the experiment away from lower CPUs (e.g., CPU 0) since a lot of background daemons run on those CPUs inside Google.

**Comment by Msiavashi** [comment]
Shinjuku's experiment worked successfully. I have some clues now to get my webserver working with the Shinjuku scheduler thanks to your help. I'll integrate my webserver with PrioTable and hope it goes without a hitch.

Thanks again

**Comment by jackhumphries** [comment]
Yes let us know. A key point is that you need to add a pthread to the PrioTable as soon as it is spawned, so make sure to allocate a large enough PrioTable when the server starts.

Depending on the scheduling policy and the scheduling hints from the server that your research requires, it may make sense to ditch the PrioTable altogether since it becomes a bottleneck at high thread counts (since the agent needs to scan the table). You could use Shinjuku or FIFO as a starting point and then take out the PrioTable and slim down other irrelevant parts of the policies.

**Comment by Msiavashi** [comment]
Dear @jackhumphries,

I used the orchestrators as samples and implemented a very simple demonstration to get familiar with the code. Here is my code:

```cpp

void printHelloWorld(uint32_t num){
    cout << "Hello World" << endl;
}


int main(int argc, char const *argv[])
{
    ghost_test::Ghost ghost_(1, 1);
    ghost_test::ExperimentThreadPool thread_pool_(1);
    vector<ghost::GhostThread::KernelScheduler> kernelSchedulers;
    vector<function<void (uint32_t)>> threadWork;
    kernelSchedulers.push_back(ghost::GhostThread::KernelScheduler::kGhost);
    threadWork.push_back(&printHelloWorld);
    thread_pool_.Init(kernelSchedulers, threadWork);
    ghost::sched_item si;
    ghost_.GetSchedItem(0, si);
    si.sid = 0;
    si.gpid = thread_pool_.GetGtids()[0].id();
    si.flags |= SCHED_ITEM_RUNNABLE;
    ghost_.SetSchedItem(0, si);
    return 0;
}

```
As you can see, I create only 1 ghOSt thread, assigned my `printHelloWorld` function to it and mark it as `RUNNABLE`. The Shinjuku agent does not crash and successfully schedules the task, however, I get multiple prints in my stdout, although I only print once. Here is the output:

```
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
[2] 0x5575a4913104 : main
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
Hello World
[3] 0x7f14c895b0b3 : __libc_start_main
Hello World
Hello World
Hello World
```
Any idea why this repetition happens? Am I missing something?

My second question is, how is it possible to ditch the PrioTable? Is it easily possible with the current implementation or it requires a new implementation of Shinjuku? I assume it should not be easy to achieve this with the current implementation of its agent. I'm I correct?

Thanks

**Comment by jackhumphries** [comment]
Hi Mohammad,

In the experiments directory, we have a helper thread pool that runs a thread body over and over again until the thread is marked as ready to exit. Below is some updated code that prints "Hello World" only once, as you would expect. Just update the include paths to work with your build.

```
#include <functional>
#include <iostream>
#include <vector>

#include "third_party/absl/synchronization/notification.h"
#include "third_party/ghost/experiments/shared/ghost.h"
#include "third_party/ghost/experiments/shared/thread_pool.h"
#include "third_party/ghost/lib/base.h"
#include "third_party/ghost/lib/ghost.h"

void printHelloWorld(uint32_t num, absl::Notification* printed,
                     absl::Notification* wait) {
  std::cout << "Hello World" << std::endl;
  printed->Notify();
  wait->WaitForNotification();
}

int main(int argc, char const* argv[]) {
  ghost_test::Ghost ghost_(1, 1);
  ghost_test::ExperimentThreadPool thread_pool_(1);
  std::vector<ghost::GhostThread::KernelScheduler> kernelSchedulers;
  std::vector<std::function<void(uint32_t)>> threadWork;
  kernelSchedulers.push_back(ghost::GhostThread::KernelScheduler::kGhost);

  absl::Notification printed;
  absl::Notification wait;
  threadWork.push_back(
      std::bind(printHelloWorld, std::placeholders::_1, &printed, &wait));

  thread_pool_.Init(kernelSchedulers, threadWork);
  ghost::sched_item si;
  ghost_.GetSchedItem(0, si);
  si.sid = 0;
  si.gpid = thread_pool_.GetGtids()[0].id();
  si.flags |= SCHED_ITEM_RUNNABLE;
  ghost_.SetSchedItem(0, si);

  printed.WaitForNotification();
  thread_pool_.MarkExit(/*sid=*/0);
  wait.Notify();
  thread_pool_.Join();

  return 0;
}
```

Basically, I use notifications to wait for the ghOSt thread to print once, then I mark the ghOSt thread as ready to exit which causes the thread pool to let it exit. Then I call `Join()` on the thread pool which avoids triggering the CHECK in the thread pool destructor, which I can see was triggered in your output.

You can modify the thread pool to avoid the repeating behavior or just create the ghOSt threads directly yourself.

If you want to ditch the PrioTable altogether (which I would recommend for your case), then I would take a look at the SOL scheduler. It is a centralized FIFO scheduler without a PrioTable. The only downside is that it is not preemptive, but you can implement this very easily yourself. On each iteration of the global scheduling loop, see how long each thread has been running so far and then schedule something else on a CPU whose currently running thread has exceeded the time slice.

**Comment by jackhumphries** [comment]
Hi Mohammad,

Please let me know if you have any additional questions. I will close this thread for now.
