### ISSUE TITLE
par file generation.

### ISSUE THREAD

**Issue by john-liu2039** [google/ghost-userspace#11]
Hi, 
It's my first time to use 'bazel' and just come across a very naive question....
It looks like some par files are required by the `GetPar()` function in `experiment/scripts/setup.py`.
I used the `bazel build -c opt ...` to compile the code but it didn't generate the par file...
Did I miss anything? Any idea where I should configure it?

Any advises will be appreciated!

**Comment by jackhumphries** [comment]
Hi John,

Please try the following, for each PAR file:

`bazel build -c opt experiments/scripts/centralized_queuing.par`

Then, run each PAR file directly (i.e., do not use `bazel run`):

`bazel-bin/experiments/scripts/centralized_queuing.par cfs ghost`

Let me know if this works.

**Comment by john-liu2039** [comment]
Thanks so much for your help, Jack:) 
It works for me and does help me understand the usage of bazel and subpar.
I'm going to close this issue.
I really appreciate your time and help!

**Comment by cashey** [comment]
1.do you mean the command as follows are the same?
bazel-bin/experiments/scripts/centralized_queuing.par shinjuku ghost
bazel run //experiments/scripts:shinjuku ghost
2.is there any difference in the end of the command 'ghost' delete? or what is the mean of the end of the command 'ghost'
@jackhumphries @john-liu2039
