### ISSUE TITLE
How to get scheduled threads information with shinjuku scheduler ? 

### ISSUE THREAD

**Issue by NGUETOUM** [google/ghost-userspace#12]
Hello, Please excuse me i have a problem and it is not error during the scheduler execution but i need to have please more explanation about some event that i have observe.
I have reach to make threads migration during the execution of shinjuku scheduler by setting my threads in my userspace application on a PrioTable as @jackhumphries had tell me.
But when the threads has migrated, i just get information about ShinjukuSchedParams not some information about threads state an so on as you can see on this image:
 
![image](https://user-images.githubusercontent.com/19855011/154780330-44e838d1-ec68-4ef4-8c65-927693bf3ba8.png)

I think that this is because the following instruction on **shinjuku_scheduler.cc** inside the **DumpAllTask()** method is never execute:

_allocator()->ForEachTask([](Gtid gtid, const ShinjukuTask* task) {
    absl::FPrintF(stderr, "%-12s%-12s%c\n", gtid.describe(),
                  ShinjukuTask::RunStateToString(task->run_state),
                  task->prio_boost ? 'P' : '-');
    return true;
  });_

To reach to execute this method i have just change this instruction **global_scheduler_->debug_runqueue_ = false;** to **global_scheduler_->debug_runqueue_ = true;** as you can see in the following image:
![image](https://user-images.githubusercontent.com/19855011/154780636-2e2604b1-c406-413a-9fc8-0cda3ef2ba51.png)

Please someone can tell me what i am suppose to do before to execute that instruction for getting those information about threads state?

**Comment by NGUETOUM** [comment]
Ok Sir. I apply it now and thank so much for your presence.

**Comment by jackhumphries** [comment]
From what you posted, my understanding is that your concern is that `allocator()-> ForEachTask() { ... }` is not printing thread state. I took a quick look at your code and it seems like all four threads are being spawned and then exiting very quickly. Thus, it is likely that all threads are dead before the `allocator()->ForEachTask()` runs which is why nothing is printed about them (because the threads do not exist anymore), though the shared memory PrioTable persists which is why you see that printed.

If you run `agent_shinjuku` with verbose mode on (e.g., `--verbose 3`), do see you messages about the threads being printed? Are any messages still being printed when you would expect `allocator()->ForEachTask()` to also print thread state?

**Comment by NGUETOUM** [comment]
It is ok now Sir.

**Comment by NGUETOUM** [comment]
As you have say that the allocator()->ForEachTask() don't print nothing because before that this function is execute all those threads have finish their execution. I have modify the function executed by each thread in the script that I show you by apply sleep(3) after each printf in that function and now the scheduler print the state of each thread as you can see in this image:

![image](https://user-images.githubusercontent.com/19855011/154784302-9df9dd0e-0748-423e-8c72-ac98064331f4.png)

**Comment by NGUETOUM** [comment]
But Sir I have another preoccupation, there I am see that for those 10 threads the scheduler schedule them in order. I think that it is because all of them have the same priority ? And if I want to change the thread priority on shed_item before to spawn those threads how i am suppose to do since the struct shed_item don't contain priority variable ?

**Comment by NGUETOUM** [comment]
Hi, @jackhumphries 
Thanks so much for your help, it is OK for me and now I reach to print information about threads state during scheduling normally. Thanks.

**Comment by jackhumphries** [comment]
Glad you got it working. The threads are scheduled in round-robin order and each thread's priority is determined by the QoS value of the work class it is in. If you would like the scheduler to make different policy decisions or have access to more information about the threads, you will need to modify the code.

**Comment by NGUETOUM** [comment]
Ok Sir, and thanks so much.
