### ISSUE TITLE
Compile agent_shinjuku in raspberry pi 4

### ISSUE THREAD

**Issue by john-liu2039** [google/ghost-userspace#15]
Hi, 

I want to get ghost-userspace working on the raspberry pi 4. So, I modified the kernel configuration and get the 5.11+ kernel compiled and installed on RPI4. Until this step, everything looks good.

Then, I `apt-get install` the required package and compiled/installed the bazel 5.2 from scratch.
Issues come out while I'm trying to `sudo bazel build -c opt agent_shinjiku`:
The top of the error message: 
```
ERROR: /home/ubuntu/ghost-userspace/BUILD:33:11: Compiling lib/enclave.cc failed: (Exit 1): linux-sandbox failed: error executing command 
  (cd /root/.cache/bazel/_bazel_root/a45884f0d9c9471c8dde34f8ae70b628/sandbox/linux-sandbox/103/execroot/com_google_ghost && \
  exec env - \
    PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin \
    PWD=/proc/self/cwd \
    TMPDIR=/tmp \
  /root/.cache/bazel/_bazel_root/install/5d68add8a862e0c465e5b7d6cddc0f77/linux-sandbox -t 15 -w /root/.cache/bazel/_bazel_root/a45884f0d9c9471c8dde34f8ae70b628/sandbox/linux-sandbox/103/execroot/com_google_ghost -w /tmp -w /dev/shm -D -- /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/aarch64-opt/bin/_objs/agent/enclave.d '-frandom-seed=bazel-out/aarch64-opt/bin/_objs/agent/enclave.o' -iquote . -iquote bazel-out/aarch64-opt/bin -iquote external/com_google_absl -iquote bazel-out/aarch64-opt/bin/external/com_google_absl -isystem bazel-out/aarch64-opt/bin/external/linux/libbpf/include '-std=c++17' -Wno-sign-compare -DGHOST_LOGGING -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c lib/enclave.cc -o bazel-out/aarch64-opt/bin/_objs/agent/enclave.o)
```
The tail of the error message:
```
/tmp/ccAPf5Pj.s: Assembler messages:
/tmp/ccAPf5Pj.s:2496: Error: unknown mnemonic `pause' -- `pause'
/tmp/ccAPf5Pj.s:12185: Error: unknown mnemonic `pause' -- `pause'
1648844166.528682230: src/main/tools/linux-sandbox-pid1.cc:498: wait returned pid=2, status=0x100
1648844166.528754655: src/main/tools/linux-sandbox-pid1.cc:516: child exited normally with code 1
1648844166.529752103: src/main/tools/linux-sandbox.cc:233: child exited normally with code 1
```
The intermediate message is in this log.[compile.log](https://github.com/google/ghost-userspace/files/8401068/compile.log)

I tried to look for the possible issue, but the solutions vary. 
Any idea or suggestion will be greatly appreciated!

**Comment by john-liu2039** [comment]
I think I may figure out the issue:)
The asm `pause` instruction used in `enclave.cc` is an X86 instruction that is not supported by aarch64.
I changed it to the `yield` instruction that made it passed the compile.
I'm wondering is there anyway to verify the correctness?
Bests,
John

**Comment by jackhumphries** [comment]
Yes, that's the correct way to fix this issue. You can call a function like the following in place of `asm volatile("pause");` so that the same code works for multiple architectures:

```
inline void Pause() {
#ifndef __GNUC__
#error "GCC is needed for the macros in the `Pause()` function."
#endif
#if defined(__x86_64__)
  asm volatile("pause");
#elif defined(__aarch64__)
  asm volatile("yield");
#elif defined(__powerpc64__)
  asm volatile("or 27,27,27");
#else
  // Do nothing.
#endif
}
```

Could you please clarify what you mean about verifying correctness? If you replace the `pause` instruction with `yield` for code compiled to `aarch64`, then you should be good.

**Comment by jackhumphries** [comment]
Feel free to reopen if you have any additional questions.

**Comment by john-liu2039** [comment]
Hi, Jack, @jackhumphries 
Thanks for the reply, and sorry for the late reply:) Finally got time to move on to this new project. Not sure whether I should keep all my problems to one issue or not.

I'm trying to run: `bazel run fifo_agent`.
I have a new question about the L3 cache check in lib/Topology.c(line 311) that RPI-4B does not have an L3 cache. But the comments on this function is for the NUMA CPU. Could that be some wrong configuration on my side? If not, would you mind providing any ideas about modifying the function? 

I really appreciate that!

Bests,
JOhn

**Comment by jackhumphries** [comment]
Hi John,

Feel free to open a new issue each time. This way it is easier for other people who are having the same issue to find our discussion.

The Topology class will currently fail to construct if there is no L3 cache on your machine, though I actually updated the Topology class in our internal codebase recently so that it will constructs without an L3 (this should fix your issue). Let me see if we are able to prioritize getting that pushed into the open source repo. If we can't get prioritize it, I'll post the patch here for you.

Jack

**Comment by john-liu2039** [comment]
Thanks so much for helping me out!! 
I will open an issue next time. Looking forward to the new patch:) Meanwhile, I can work on odroid n2 which is a real heterogeneous platform. 
Thanks again:)

**Comment by jackhumphries** [comment]
Hi John,

We just pushed this in commit https://github.com/google/ghost-userspace/commit/1c09b7447f33833e15e3e029199122f1fd429d27. Please let me know if this works for you.

Jack

**Comment by john-liu2039** [comment]
Thanks, Jack!
Just test it with FIFO scheduler and hello world binary. The new patch works on the RPI4 and odroid n2:) 
Bests,
John
