### ISSUE TITLE
How to solve "bazel-out/k8-opt/bin/external/linux/libbpf/include/libbpf/bpf.h:244:6: error: use of enum 'bpf_stats_type' without previous declaration??"

### ISSUE THREAD

**Issue by kirchhoff** [google/ghost-userspace#17]
![image](https://user-images.githubusercontent.com/2253887/166107125-2f4d9e00-39f9-49db-b64a-3181f87e5363.png)

**Comment by kirchhoff** [comment]
wdkirchhoff@vmware:~/ghost-userspace$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by kirchhoff** [comment]
I just add the following code :
enum bpf_stats_type
#ifdef __cplusplus
: int
#endif
; /* defined in up-to-date linux/bpf.h */
in bpf/user/agent.h to make it build successfully.

**Comment by jackhumphries** [comment]
Hello,

I believe https://github.com/google/ghost-userspace/issues/3 should contain the solution to your problem. This issue is likely happening because you need to install the kernel headers for the ghOSt kernel. From the ghOSt kernel tree, run `make headers_install INSTALL_HDR_PATH=/usr`. Please let me know if this fixes your issue.

Jack

**Comment by jackhumphries** [comment]
Feel free to reopen if you are still having this issue.

**Comment by kirchhoff** [comment]
> Hello,
> 
> I believe #3 should contain the solution to your problem. This issue is likely happening because you need to install the kernel headers for the ghOSt kernel. From the ghOSt kernel tree, run `make headers_install INSTALL_HDR_PATH=/usr`. Please let me know if this fixes your issue.
> 
> Jack

Yes, It fixes my issue. 
Great thanks!!!
