### ISSUE TITLE
Which measurement unit is used when we get runtime value from kernel with status_word ?

### ISSUE THREAD

**Issue by NGUETOUM** [google/ghost-userspace#23]
Hi, 
Good morning to you all, I just have a simple question, I want to know which measurement unit is used when we get runtime value from kernel. For example by doing something like task->status_word.runtime(). It is a Millisecond unit or Microsecond unit or Nanosecond unit which is used since the runtime function just return uint64_t value ? Thanks for your help.

**Comment by jackhumphries** [comment]
The runtime in status words is in units of nanoseconds. Hope this helps.
