### ISSUE TITLE
I am getting this error when running the simple_exp after running the ghost CFS scheduler

### ISSUE THREAD

**Issue by souravpaul8** [google/ghost-userspace#25]
<img width="607" alt="Screenshot 2022-10-28 at 11 29 59 AM" src="https://user-images.githubusercontent.com/37119302/198514570-5337a3a6-c557-49d6-a4cb-6db08902f693.png">

**Comment by dohyunkim-dev** [comment]
Thank you for reporting this issue. I was able to replicate this bug on this repo's HEAD. This issue seems to be resolved in a more up-to-date CFS agent implementation in our internal repo - I will push more changes to this public repo and update this issue once I can see this bug gone.

**Comment by souravpaul8** [comment]
@dohyunkim-dev Is there any way I can schedule the ghost thread experiment in the default linux cfs scheduler explicitly ?

**Comment by cashey** [comment]
![image](https://user-images.githubusercontent.com/34826891/206989918-943efff4-993b-46e0-91ce-a282373c3f03.png)
