### ISSUE TITLE
I am getting this error when I run bazel build -c opt fifo_per_cpu_agent

### ISSUE THREAD

**Issue by aghari19** [google/ghost-userspace#26]
![Screenshot from 2022-11-07 14-32-42](https://user-images.githubusercontent.com/47031270/200398632-58c8a12c-82c8-42fb-af8f-ea5e8ca85e3e.png)

**Comment by dohyunkim-dev** [comment]
Hi @aghari19 , this seems to be related to another issue #3. Could you:

1. make sure you are in ghOSt kernel (`uname -a`)
2. run `make headers_install INSTALL_HDR_PATH=/usr` in the `ghost-kernel`'s directory
3. check whether you see the declaration for enum bpf_stats_type in /usr/src/linux-headers-VERSION/include/uapi/linux/bpf.h? Replace VERSION in the path with the ghOSt kernel version (5.11 or so).

**Comment by aghari19** [comment]
Hello @dohyunkim-dev 
Thank you for your pointers. I rebuilt the system and ran the make command and was able to successfully build the user-space. 

However, soon after I run into the following issue when I run the following command: 
bazel-bin/fifo_per_cpu_agent --ghost_cpus 0-1



![Screenshot from 2022-11-22 13-40-40](https://user-images.githubusercontent.com/47031270/203395678-c2991b50-f7d2-499f-8715-50d5330394ae.png)

**Comment by jackhumphries** [comment]
Hello,

It appears that you may not have the ghOSt kernel installed, or if you do, then perhaps `CONFIG_SCHED_CLASS_GHOST` was not set.

To check if the ghOSt kernel was installed with ghOSt enabled, can you let me know if you see the `ghost` directory under `/sys/fs`?

Thanks,
Jack

**Comment by aghari19** [comment]
Hello Jack, 
Yes, I think the ghost kernel was not installed or if it did it was not proper. I do not see the ghost directory under /sys/fs and when I looked for the CONFIG_SCHED_CLASS_GHOST in the .config file it was not set. 
I see this in the config file. 
![Screenshot from 2022-11-23 11-13-20](https://user-images.githubusercontent.com/47031270/203595468-d96d50b3-81f9-471b-80a3-4d1c790230c4.png)

While configuring the kernel do you recommend doing 'make menuconfig' and enabling the ghost class or doing 'make defconfig'. 

I have been doing defconfig all this while. Please let me know, 

Thank you, 
Haritha

**Comment by dohyunkim-dev** [comment]
Hi aghari19, sorry for the delayed response. As long as you can get the setting that works, you can use either menuconfig or defconfig. I personally use ./scripts/config --enable CONFIG_SCHED_CLASS_GHOST before doing `make` to make sure ghOSt is properly configured for compilation. Marking this thread as closed, but feel free to reopen and follow up if you have any further questions.
