### ISSUE TITLE
When running 'sudo bazel-bin/pushtosched 18', I encountered an error: sched_setscheduler(1) failed: Bad file descriptor'"

### ISSUE THREAD

**Issue by lhpqaq** [google/ghost-userspace#29]
When running 'sudo bazel-bin/pushtosched 18', I encountered an error: sched_setscheduler(1) failed: Bad file descriptor'"
Can someone give me a hint?

**Comment by jackhumphries** [comment]
`pushtosched` was updated in January. It now only supports moving threads into CFS.

To move threads into ghOSt, write the TIDs directly directly to the enclave's task file. Example:
```
cat /dev/cgroup/cpu/your/tasks > /sys/fs/ghost/enclave_X/tasks
```

**Comment by lhpqaq** [comment]
> `pushtosched` was updated in January. It now only supports moving threads into CFS.
> 
> To move threads into ghOSt, write the TIDs directly directly to the enclave's task file. Example:
> 
> ```
> cat /dev/cgroup/cpu/your/tasks > /sys/fs/ghost/enclave_X/tasks
> ```

Can I use it to schedule kernel threads? When I tried to use it to schedule root threads, I failed.

**Comment by lhpqaq** [comment]
> > `pushtosched` was updated in January. It now only supports moving threads into CFS.
> > To move threads into ghOSt, write the TIDs directly directly to the enclave's task file. Example:
> > ```
> > cat /dev/cgroup/cpu/your/tasks > /sys/fs/ghost/enclave_X/tasks
> > ```
> 
> Can I use it to schedule kernel threads? When I tried to use it to schedule root threads, I failed.

I have succeeded, thank you！
