### ISSUE TITLE
How to add a custom scheduler? Is it possible for me to get some help?

### ISSUE THREAD

**Issue by lhpqaq** [google/ghost-userspace#33]
I want to design a preemptive scheduler myself, but it is difficult to learn the code at present. Does ghost provide public guidance?

**Comment by jackhumphries** [comment]
We don't have additional documentation beyond the README file and code comments in this repository. I would suggest looking at the centralized FIFO scheduler in `schedulers/fifo/centralized/`. This scheduler is less complex than the others and supports preemption. The core of the scheduler is `GlobalSchedule()` in `fifo_scheduler.cc`, and there is an if statement that checks if the task on each CPU has met/exceeded its time slice and should be preempted.

**Comment by lhpqaq** [comment]
> We don't have additional documentation beyond the README file and code comments in this repository. I would suggest looking at the centralized FIFO scheduler in `schedulers/fifo/centralized/`. This scheduler is less complex than the others and supports preemption. The core of the scheduler is `GlobalSchedule()` in `fifo_scheduler.cc`, and there is an if statement that checks if the task on each CPU has met/exceeded its time slice and should be preempted.
> 
> If you have any questions, we are happy to help!
After testing, I found that there was preemption, but the time slot was a little long. I have read the code of schedulers/fifo/centralized/many times, but I can't find where the time slice and preemption occur. Can you give me a hint?

**Comment by jackhumphries** [comment]
The time slice preemption check occurs [here](https://github.com/google/ghost-userspace/blob/main/schedulers/fifo/centralized/fifo_scheduler.cc#L275). Specifically, the following if statement checks if the current task on a CPU should continue running:
```
if (cs->current &&
    (MonotonicNow() - cs->last_commit) < preemption_time_slice_) {
  // This CPU is currently running a task, so do not schedule a different
  // task on it.
  continue;
}
```

If the if statement evaluates to false, then `available.Set(cpu);` runs after the if statement body, so the CPU is eligible to have another task scheduled onto it. If another task is scheduled onto the CPU, then the current task on the CPU will be preempted.

**Comment by lhpqaq** [comment]
> The time slice preemption check occurs [here](https://github.com/google/ghost-userspace/blob/main/schedulers/fifo/centralized/fifo_scheduler.cc#L275). Specifically, the following if statement checks if the current task on a CPU should continue running:
> 
> ```
> if (cs->current &&
>     (MonotonicNow() - cs->last_commit) < preemption_time_slice_) {
>   // This CPU is currently running a task, so do not schedule a different
>   // task on it.
>   continue;
> }
> ```
> 
> If the if statement evaluates to false, then `available.Set(cpu);` runs after the if statement body, so the CPU is eligible to have another task scheduled onto it. If another task is scheduled onto the CPU, then the current task on the CPU will be preempted. Note that if another task is not scheduled onto the CPU (e.g., because there are no runnable tasks in the runqueue), then the current task will continue running on the CPU even though it has exceeded its time slice.

Thank you. I didn't update the code of the depository locally. I used the code of 2022 and didn't find the preempted part.
After I update the local userspace code, run
Get error:
```
Fatal error!
Ghost version 75 not supported
Kernel supports versions: 69 
Core map
(  0 )	(  1 )	(  2 )	(  3 )	
Initializing...
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
F0000 00:00:1678063929.016247    8737 enclave.cc:427] Check failed: ctl_fd_ >= 0 (-1 vs. 0) 
*** Check failure stack trace: ***
    @     0x5576fd517644  absl::log_internal::LogMessage::Flush()
    @     0x5576fd51775d  absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @     0x5576fd50ce80  ghost::LocalEnclave::CreateAndAttachToEnclave()
    @     0x5576fd50d0c5  ghost::LocalEnclave::LocalEnclave()
    @     0x5576fd4de027  ghost::FullFifoAgent<>::FullFifoAgent()
    @     0x5576fd4df1b4  ghost::AgentProcess<>::AgentProcess()
    @     0x5576fd4db50e  main
    @     0x7f6a5877b0b3  __libc_start_main
```
Do I have to update the kernel?

**Comment by jackhumphries** [comment]
Yes, you need to update the kernel repository as well.

**Comment by ZhaoNeil** [comment]
> > We don't have additional documentation beyond the README file and code comments in this repository. I would suggest looking at the centralized FIFO scheduler in `schedulers/fifo/centralized/`. This scheduler is less complex than the others and supports preemption. The core of the scheduler is `GlobalSchedule()` in `fifo_scheduler.cc`, and there is an if statement that checks if the task on each CPU has met/exceeded its time slice and should be preempted.
> > If you have any questions, we are happy to help!
> 
> After testing, I found that there was preemption, but the time slot was a little long. I have read the code of `schedulers/fifo/centralized/`many times, but I can't find where the time slice and preemption occur. Can you give me a hint?

Could you let me know how did you test the preemption?

**Comment by lhpqaq** [comment]
> 

分配2个cpu，添加3+个任务到ghost，都能执行到说明有抢占

**Comment by lhpqaq** [comment]
> > > We don't have additional documentation beyond the README file and code comments in this repository. I would suggest looking at the centralized FIFO scheduler in `schedulers/fifo/centralized/`. This scheduler is less complex than the others and supports preemption. The core of the scheduler is `GlobalSchedule()` in `fifo_scheduler.cc`, and there is an if statement that checks if the task on each CPU has met/exceeded its time slice and should be preempted.
> > > If you have any questions, we are happy to help!
> > 
> > 
> > After testing, I found that there was preemption, but the time slot was a little long. I have read the code of `schedulers/fifo/centralized/`many times, but I can't find where the time slice and preemption occur. Can you give me a hint?
> 
> Hi, could you let me know how did you verify the preemption?

分配2个cpu，添加3+个任务到ghost，都能执行到说明有抢占

**Comment by lhpqaq** [comment]
> > > > > We don't have additional documentation beyond the README file and code comments in this repository. I would suggest looking at the centralized FIFO scheduler in `schedulers/fifo/centralized/`. This scheduler is less complex than the others and supports preemption. The core of the scheduler is `GlobalSchedule()` in `fifo_scheduler.cc`, and there is an if statement that checks if the task on each CPU has met/exceeded its time slice and should be preempted.
> > > > > If you have any questions, we are happy to help!
> > > > 
> > > > 
> > > > After testing, I found that there was preemption, but the time slot was a little long. I have read the code of `schedulers/fifo/centralized/`many times, but I can't find where the time slice and preemption occur. Can you give me a hint?
> > > 
> > > 
> > > Hi, could you let me know how did you verify the preemption?
> > 
> > 
> > 分配2个cpu，添加3+个任务到ghost，都能执行到说明有抢占
> 
> 你是说有任务在两个cpu上都执行到吗？

添加几个死循环的程序，如果没有抢占，两个任务会一直占用两个cpu，第三个程序就执行不了

**Comment by ZhaoNeil** [comment]
> > > > > > We don't have additional documentation beyond the README file and code comments in this repository. I would suggest looking at the centralized FIFO scheduler in `schedulers/fifo/centralized/`. This scheduler is less complex than the others and supports preemption. The core of the scheduler is `GlobalSchedule()` in `fifo_scheduler.cc`, and there is an if statement that checks if the task on each CPU has met/exceeded its time slice and should be preempted.
> > > > > > If you have any questions, we are happy to help!
> > > > > 
> > > > > 
> > > > > After testing, I found that there was preemption, but the time slot was a little long. I have read the code of `schedulers/fifo/centralized/`many times, but I can't find where the time slice and preemption occur. Can you give me a hint?
> > > > 
> > > > 
> > > > Hi, could you let me know how did you verify the preemption?
> > > 
> > > 
> > > 分配2个cpu，添加3+个任务到ghost，都能执行到说明有抢占
> > 
> > 
> > 你是说有任务在两个cpu上都执行到吗？
> 
> 添加几个死循环的程序，如果没有抢占，两个任务会一直占用两个cpu，第三个程序就执行不了

多谢老哥！
