### ISSUE TITLE
some question about switchTo and Latched

### ISSUE THREAD

**Issue by liu-delong** [google/ghost-userspace#34]
I am very sorry to disturb you, but I have something really want to know about ghOSt.
I have two questions about the following codes,which is written in schedules`/fifo/per_cpu/fifo_schedules.cc` :
```
if (payload->from_switchto) {
    Cpu cpu = topology()->cpu(payload->cpu);
    enclave()->GetAgent(cpu)->Ping();
  }
```
- The first question is:what does “`from_switchto`” means?Under what circumstances will "`from_swichto`" not be 0? 
- The second question is:I think “enclave()->GetAgent(cpu)->Ping()” can be excuted means the agent is running.So why we do we need to ping the agent?

Besides,I have another two questions:
- 1.Under what circumstances will we received a MSG_TASK_SWITCHTO?In other words, what does "MSG_TASK_SWITCHTO" mean?
- 2.Under what circumstances will we received a MSG_TASK_LATCHED?In other words, what does "MSG_TASK_LATCHED" mean?

I’d be greatly grateful if you could answer my questions and I’m very looking forward to your reply!

**Comment by jackhumphries** [comment]
Hi,

Please disregard any code that references SwitchTo. This is an internal Google kernel feature that we do not include in the open source ghOSt kernel, though there are still references to it in the ghOSt kernel. Thus, no SwitchTo code will run in ghOSt. If you are interested, you can learn more about SwitchTo here: https://www.youtube.com/watch?v=KXuZi9aeGTw

`MSG_TASK_LATCHED` is an optional message that is delivered when a task is successfully committed on a CPU. At this point, the task is "latched," meaning that the kernel will context switch to it when `pick_next_task()` is called on that CPU and no higher priority scheduling classes have tasks to run. This message is only delivered when the `SEND_TASK_LATCHED` is set in the transaction run flags. Please note that we have removed the `MSG_TASK_LATCHED` message type internally, so it will be taken out of the open source repo as well once those commits reach the open source repo.

**Comment by liu-delong** [comment]
Your answer has resolved my question, I am truly grateful for your help, thank you!
