### ISSUE TITLE
Questions about enclave

### ISSUE THREAD

**Issue by GaoDong666** [google/ghost-userspace#38]
Hello, ALL.

It seems that the _enclaves_ in ghOSt is implemented through Linux's _cgroup_, which is an OS-level resource isolation solution. 

I wonder if the _enclave_ in this paper has any connection with Intel’s __Software Guard Extensions_ (SGX)_ technology? If so, does it mean that ghOSt can only run on Intel processors with SGX support?

Thank You!

**Comment by jackhumphries** [comment]
Enclaves are implemented by the ghOSt code itself rather than through cgroups. For example, please take a look at `create_enclave()` in `kernel/sched/ghost.c`.

ghOSt enclaves do not have any connection to Intel SGX. ghOSt can run on any processor, including Intel, AMD, and ARM.
