### ISSUE TITLE
questions about MSG_TASK_ON_CPU

### ISSUE THREAD

**Issue by liu-delong** [google/ghost-userspace#40]
hi,
Could you please help me understand under what circumstances the message "MSG_TASK_ON_CPU" is generated? I have not seen this message being issued by the kernel in most cases. Is there a particular configuration required to enable the kernel to send this message? Thank you very much for your assistance.

**Comment by jackhumphries** [comment]
This message is sent when the run flags for the transaction include the `SEND_TASK_ON_CPU` flag. When the task scheduled by the transaction gets on CPU, the message is then sent. Take a look at `ghost_task_got_oncpu()` in `kernel/sched/ghost.c` in the kernel.
