### ISSUE TITLE
Questions about running multiple concurrent policies on a single machine using multiple enclaves.

### ISSUE THREAD

**Issue by ZhaoNeil** [google/ghost-userspace#44]
Hi,

Since ghost is able to run multiple concurrent policies on a single machine using multiple enclaves, so I can open two terminals to run two different schedulers concurrently by specifying groups of cpus. But now it involves the following questions:

1. How to correctly run multiple concurrent policies on a single machine using multiple enclaves?
2. When a new task arrives, which enclave does it enter, and what rules does it follow?
3. Is it possible to move one running task from one enclave to another? If possible, how to do it?

**Comment by show981111** [comment]
@ZhaoNeil Hey, I am trying to achieve a similar thing.
Have you figured out how to run multiple agents and switch among them?

**Comment by ZhaoNeil** [comment]
> @ZhaoNeil Hey, I am trying to achieve a similar thing. Have you figured out how to run multiple agents and switch among them?

Hi, for multiple agents you could check the code in schedulers/fifo/per_cpu/fifo_scheduler. Every CPU maintains an agent. But the question from me is that we have multiple enclaves at the same time rather than multiple agents.

**Comment by dohyunkim-dev** [comment]
Hi ZhaoNeil and show981111, sorry for the delayed response.

Yes, ghOSt is able to run multiple concurrent policies on a single machine, each policy attached to each enclave. You can have at most one enclave attached to each CPU, so your enclaves will get their own non-overlapping subsets of CPUs in the machine. For instance, you can create enclave_1 for CPU 0-3 and enclave_2 for CPU 4-7 on an 8-CPU machine. However, you cannot attach a CPU to both enclaves. To set up this CPU list, you can write to enclave's cpulist file.  i.e., `echo 0-3 > /sys/fs/ghost/enclave_1/cpulist` and `echo 4-7 > /sys/fs/ghost/enclave_2/cpulist`. Or, our C++ library supports passing class CpuList when creating an enclave. See our tests and schedulers for examples.

You can put any task into any enclave by writing the ID to enclave's `tasks` file. For example, if your task has ID 1234, you can do `echo 1234 > /sys/fs/ghost/enclave_1/tasks` to put that task in to enclave_1. Then, if you want to move this task to another enclave (say enclave_2), you can kick this task out of ghOSt via `sched_setscheduler(policy=SCHED_OTHER)` and put into enclave_2 by `echo 1234 > /sys/fs/ghost/enclave_2/tasks`.

For having multiple agents in a single enclave, you can implement whatever policy you want on top of our C++ library.

Hope this helps - feel free to reopen this issue if you have any follow-up questions.
