### ISSUE TITLE
Error mounting ghostfs

### ISSUE THREAD

**Issue by JaehyeongIm** [google/ghost-userspace#51]
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
F0000 00:00:1725644773.334689    2497 ghost.cc:154] Check failed: (*__errno_location ()) == 16 (2 vs. 16) 
*** Check failure stack trace: ***
    @     0x563feed2231d  absl::log_internal::LogMessage::PrepareToDie()
    @     0x563feed22395  absl::log_internal::LogMessage::SendToLog()
    @     0x563feed21e03  absl::log_internal::LogMessage::Flush()
    @     0x563feed22774  absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @     0x563feeccabf4  ghost::Ghost::MountGhostfs()
    @     0x563feeccac3d  ghost::Ghost::GetSupportedVersions()
    @     0x563feec9077c  ghost::Ghost::CheckVersion()
    @     0x563feec8ff89  __static_initialization_and_destruction_0()
    @     0x563feec8ffac  _GLOBAL__sub_I_agent.cc
    @     0x563feede05ed  __libc_csu_init
Aborted (core dumped)

"My actual PC is x86_64, and the kernel version is 5.11.0+. I am running it on VirtualBox, but I cannot mount ghostfs. When I try to use the following mount command:

mount -t ghost ghost /sys/fs/ghost
I get the following error message:
mount: /sys/fs/ghost: mount point does not exist.
How can I resolve this issue?"

**Comment by jackhumphries** [comment]
Are you running this on the kernel from https://github.com/google/ghost-kernel?

**Comment by JaehyeongIm** [comment]
It seems to be resolved now. I had cloned the kernel from https://github.com/google/ghost-kernel and was working on it. But after using the installer from https://github.com/Swire42/ghost-installer, it works fine now. Thank you
