### ISSUE TITLE
O(1) scheduler by ghost

### ISSUE THREAD

**Issue by JaehyeongIm** [google/ghost-userspace#52]
I'm working on a project to implement a new scheduler using the Ghost framework, and I'm trying to implement the old Linux default scheduler, the O(1) scheduler. Is it possible to do this?

**Comment by jackhumphries** [comment]
Yes, you can implement per-CPU scheduling with ghOSt. The most similar scheduler in the ghOSt repository is the [per-CPU FIFO scheduler](https://github.com/google/ghost-userspace/tree/main/schedulers/fifo/per_cpu). This scheduler maintains a FIFO queue of runnable tasks on a per-CPU basis. You can extend the scheduler to support per-CPU active and expired arrays.

**Comment by JaehyeongIm** [comment]
> Yes, you can implement per-CPU scheduling with ghOSt. The most similar scheduler in the ghOSt repository is the [per-CPU FIFO scheduler](https://github.com/google/ghost-userspace/tree/main/schedulers/fifo/per_cpu). This scheduler maintains a FIFO queue of runnable tasks on a per-CPU basis. You can extend the scheduler to support per-CPU active and expired arrays.

I'm trying to implement an O(1) scheduler by creating 140 priority queues instead of one queue per core. In order to do this, you have to get the priority of the task, but is it possible to get the priority?
