### ISSUE TITLE
How do I run an application to ghost core?

### ISSUE THREAD

**Issue by JaehyeongIm** [google/ghost-userspace#53]
I want to turn the application to a ghost enabled core. What should I do?

**Comment by jackhumphries** [comment]
Once a ghOSt scheduler is running, you can move an application thread into the ghOSt scheduling class using:
```
CHECK_EQ(GhostHelper()->SchedTaskEnterGhost(/*pid=*/0, -1), 0);
```
Alternatively, you can use a `GhostThread` instead (see `tests/simple_edf.cc` for an example).

**Comment by JaehyeongIm** [comment]
> Once a ghOSt scheduler is running, you can move an application thread into the ghOSt scheduling class using:
> 
> ```
> CHECK_EQ(GhostHelper()->SchedTaskEnterGhost(/*pid=*/0, -1), 0);
> ```
> 
> Alternatively, you can use a `GhostThread` instead (see `tests/simple_edf.cc` for an example).

Thank you for answer
